server:
  port: 8083
spring:
  application:
  name: authentication-service
keycloak:
  auth-server-url: ${AUTH_SERVER_HOST}
  realm: ${KEYCLOAK_REALM}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}