spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/edunavigator-app-realm
server:
  port: 9000
services:
  ingestion:
    host: ${INGESTION_SERVICE_HOST}
    path: ${INGESTION_SERVICE_PATH}
  search:
    host: ${SEARCH_SERVICE_HOST}
    path: ${SEARCH_SERVICE_PATH}
  content:
    host: ${CONTENT_SERVICE_HOST}
    path: ${CONTENT_SERVICE_PATH}
  auth:
    host: ${AUTH_SERVICE_HOST}
    path: ${AUTH_SERVICE_PATH}
auth:
  open-urls:
    - ${register.path:""}
    - ${login.path:""}